---
- name: Check if Docker is installed
  command: which docker
  register: docker_command_result
  changed_when: false
  failed_when: false
  check_mode: no

- name: Ensure Docker is installed
  fail:
    msg: "The 'forgejo' role requires Docker to be installed. Please run the 'docker' role first."
  when: docker_command_result.rc != 0
  
- name: Create directory for Forgejo container
  file:
    path: "{{ forgejo_path }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml file for Forgejo
  template:
    src: docker-compose.yml.j2
    dest: "{{ forgejo_path }}/docker-compose.yml"
    mode: '0644'

- name: Start Forgejo container
  community.docker.docker_compose:
    project_src: "{{ forgejo_path }}"