# Docker installation tasks
---
- name: Install Docker CE dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  tags: [docker, dependencies]

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [docker, repository]

# Use a safer approach for determining OS codename 
- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }}/{{ ansible_lsb.codename | default(ansible_distribution_release | lower) }} stable"
    state: present
    filename: docker
  tags: [docker, repository]

- name: Install Docker CE and CLI
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present  # Using 'present' instead of 'latest' for better idempotency
    update_cache: yes
  tags: [docker, install]

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present  # Using 'present' instead of 'latest' for better idempotency
  tags: [docker, compose]

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started
  tags: [docker, service]

- name: Set fact Docker is installed
  set_fact:
    docker_installed: true
  tags: [docker]

# Add user to docker group to allow non-root access to Docker
- name: Add user to docker group
  user:
    name: "{{ ansible_user | default('netghost') }}"
    groups: docker
    append: yes
  tags: [docker, user]