# LazyDocker installation tasks
---
# Check LazyDocker installation status to maintain idempotency
- name: Check if LazyDocker is already installed
  command: which lazydocker
  register: lazydocker_exists
  changed_when: false
  failed_when: false
  check_mode: no
  tags: [lazydocker]

- name: Set fact about LazyDocker installation status
  set_fact:
    lazydocker_is_installed: "{{ lazydocker_exists.rc == 0 }}"
  tags: [lazydocker]

# Install dependencies only if LazyDocker is not installed
- name: Install dependencies for LazyDocker
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  when: not lazydocker_is_installed
  tags: [lazydocker, dependencies]

- name: Download LazyDocker
  get_url:
    url: https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_amd64.zip
    dest: /tmp/lazydocker.zip
    mode: '0644'
  when: not lazydocker_is_installed
  tags: [lazydocker, download]

- name: Unzip LazyDocker
  unarchive:
    src: /tmp/lazydocker.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
  when: not lazydocker_is_installed
  tags: [lazydocker, install]

- name: Ensure LazyDocker is executable
  file:
    path: /usr/local/bin/lazydocker
    mode: '0755'
    state: file
  when: not lazydocker_is_installed
  tags: [lazydocker, permissions]

# Clean up downloaded artifacts
- name: Cleanup LazyDocker installation files
  file:
    path: /tmp/lazydocker.zip
    state: absent
  when: not lazydocker_is_installed
  tags: [lazydocker, cleanup]