# tasks file for docker

# Include Docker installation tasks
- name: Install Docker
  import_tasks: docker.yml

# Conditionally include LazyDocker installation tasks
- name: Install LazyDocker
  import_tasks: lazydocker.yml
  when: install_lazydocker | bool
